name: 📄 Docs
description: Found an issue in the documentation? You can use this one!
title: "[Docs]: <title>"
labels: ['documentation']

body:

    -   type: markdown
        id: greet
        attributes:
            value: |
                Thanks for stopping by to let us know something could be better!
                <br>

    -   type: textarea
        id: description
        attributes:
            label: Description
            description: |
                A brief description of the question or issue, also include what you tried and what didn't work.
        validations:
            required: true

    -   type: textarea
        id: screenshots
        attributes:
            label: Screenshots
            description: |
                Please add screenshots if applicable.
                
                Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
        validations:
            required: false

    -   type: textarea
        id: extra_info
        attributes:
            label: Additional information
            description: |
                Is there anything else we should know about this issue?
        validations:
            required: false
