name: greetings

on: 
    issues:
        types:
            - opened

    issue_comment:
        types:
            - created

    pull_request_target:
        types:
            - opened

    pull_request_review_comment:
        types:
            - created

jobs:

    greeting:
        runs-on: ubuntu-latest

        permissions:
            issues: write
            pull-requests: write

        steps:

            -   uses: actions/first-interaction@v1
                with:
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

                    issue-message: |
                        Hello @${{ github.actor }} , thank you for submitting an issue! A project committer will shortly review the issue.

                    pr-message: |
                        Thank you @${{ github.actor }} , for contributing to this project, your support is much appreciated. A project committer will shortly review your contribution.
