name: release

on:
    workflow_run:
        workflows: [ "tests" ]
        branches: [ "main" ]
        types:
            - completed
    
    workflow_dispatch:

jobs:

    github-release:
        runs-on: ubuntu-latest

        environment:
            name: Staging

        steps:
            -   uses: actions/checkout@v2

            -   name: conventional Changelog Action
                id: changelog
                uses: TriPSs/conventional-changelog-action@v3.7.1
                with:
                    github-token: ${{ secrets.CHANGELOG_RELEASE }}
                    git-user-name: Google GitHub Actions Bot
                    git-user-email: 72759630+google-github-actions-bot@users.noreply.github.com
                    git-message: 'release: {version}'
                    version-file: ./pyproject.toml
                    version-path: project.version
                    release-count: 0

            -   name: create release
                uses: actions/create-release@v1
                if: ${{ steps.changelog.outputs.skipped == 'false' }}
                env:
                    GITHUB_TOKEN: ${{ secrets.CHANGELOG_RELEASE }}
                with:
                    tag_name: ${{ steps.changelog.outputs.tag }}
                    release_name: ${{ steps.changelog.outputs.tag }}
                    body: ${{ steps.changelog.outputs.clean_changelog }}
